networks:
  traefik:
    name: traefik_web
    external: true
  postgres:
    name: postgres
    external: true
  redis:
    name: redis
    external: true
  mail:
    name: mail
    external: true
  webapp:
    name: ${DOCKER_NAME}_app
    driver: bridge

services:
  app:
    container_name: "${DOCKER_NAME}_app"
    build:
      context: ./.devops/docker/laravel
      dockerfile: Dockerfile
      args:
        - PUID=${DOCKER_PUID:-1000}
        - PGID=${DOCKER_PGID:-1000}
        - WWWUSER=${DOCKER_USER:-laravel}
    image: ${DOCKER_NAME}/laravel
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./:/var/www:cached
      - ./.devops/docker/data/laravel/logs:/var/log/supervisor
      - ../laravel-repository:/var/www/laravel-repository
    labels:
      - "traefik.enable=false"
    networks:
      - webapp
      - postgres
      - redis
      - mail

  server:
    container_name: "${DOCKER_NAME}_server"
    build:
      context: ./.devops/docker/server
      dockerfile: Dockerfile
    image: ${DOCKER_NAME}/server
    volumes:
      - ./:/var/www:cached
      - ./.devops/docker/data/nginx/logs:/var/log/nginx:rw
      - ./.devops/docker/server/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.devops/docker/server/laravel-site.conf:/etc/nginx/sites-enabled/laravel-site.conf:ro
    depends_on:
      - app
    networks:
      - webapp
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      # - "traefik.http.routers.${DOCKER_NAME}.tls=true"
      - "traefik.http.routers.${DOCKER_NAME}.rule=Host(`${BASE_DOMAIN}`)"
      - "traefik.http.services.${DOCKER_NAME}.loadbalancer.server.port=80"
      - "traefik.http.services.${DOCKER_NAME}.loadbalancer.passhostheader=true"
